rango/urls.py
from django.urls import path
from rango import views
from rango.views import AboutView, AddCategoryView, IndexView
from rango.views import ShowCategoryView, AddPageView, RestrictedView
from rango.views import GoToView, RegisterProfileView, ProfileView, ListProfilesView

app_name='rango'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', IndexView.as_view(), name='index'),
    # path('about/', views.about, name='about'),
    path('about/', AboutView.as_view(), name='about'),
    # path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/', ShowCategoryView.as_view(), name='show_category'),
    # path('add_category/', views.add_category, name='add_category'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    # path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<slug:category_name_slug>/add_page/', AddPageView.as_view(), name='add_page'),
    # path('register/', views.register, name='register'),
    # path('login/', views.user_login, name="login"),
    # path('restricted/', views.restricted, name="restricted"),
    path('restricted/', RestrictedView.as_view(), name="restricted"),
    # path('logout',  views.user_logout, name="logout"),
    path('search/', views.search, name="search"),
    # path('goto/', views.goto_url, name="goto"),
    path('goto/', GoToView.as_view(), name="goto"),
    # path('register_profile/', views.register_profile, name='register_profile'),
    path('register_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', ProfileView.as_view(), name='profile'),
    path('profiles', ListProfilesView.as_view(), name="list_profiles"),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name="suggest"),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),

]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from django.http import HttpResponse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    #adding success_url='rango:register_profile to as_view() parameter fixed redirect problem
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        # Added for the testing chapter.
        if self.views < 0:
            self.views = 0

        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.last_visit = timezone.now()
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    #This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                            help_text="Please enter the category name.")

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    #An inline class to provide additional information on the form.
    class Meta:
        #Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page.')

    url = forms.URLField(max_length=200,
                        help_text="Please enter the URL of the page.")

    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        #Provide an association between the ModelForm and a model
        model = Page

        #What fields do we need to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key
        # We can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field)
        #fields = ('title', 'uirl', 'views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from rango.forms import PageForm
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from rango.forms import UserProfile
from django.utils import timezone

class SearchAddPageView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']
        title = request.GET['title']
        url = request.GET['url']

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse('Error - category not found.')
        except ValueError:
            return HttpResponse('Error - bag category ID.')

        p = Page.objects.get_or_create(category=category,
                                        title=title,
                                        url = url)

        pages = Page.objects.filter(category=category).order_by('-views')
        return render(request, 'rango/page_listing.html', {'pages': pages})

class CategorySuggestionView(View):
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''

        category_list = get_category_list(max_results=8, starts_with=suggestion)

        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')

        return render(request,
                        'rango/categories.html',
                        {'categories': category_list})

def get_category_list(max_results=0, starts_with=''):
    category_list=[]

    if starts_with:
        category_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]

    return category_list

class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']

        try:
            category = Category.objects.get(id=int(category_id))
        except Catrgory.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        category.likes = category.likes + 1
        category.save()

        return HttpResponse(category.likes)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()

        return render(request, 'rango/list_profiles.html', {'user_profile_list': profiles})

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})

        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)

        context_dict = {'user_profile':user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)


class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)

class GoToView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except:
            return redirect(reverse('rango:index'))

        selected_page.views = selected_page.views + 1
        selected_page.last_visit = timezone.now()
        selected_page.save()

        return redirect(selected_page.url)

def goto_url(request):
    if request.method == 'GET':

        page_id = request.GET.get('page_id')

        try:
            selected_page = Page.objects.get(id=page_id)
        except:
            return redirect(reverse('rango:index'))

        selected_page.views = selected_page.views + 1
        selected_page.save()

    return redirect(selected_page.url)

def search(request):
    result_list = []
    query = ''

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            #Run our Bing function to get the results list
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    # If it's been more than a day since the last visit...
    if(datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    request.session['visits'] = visits


# #Use the login_required decorator to ensure only those logged in can
# #access the view
# @login_required
# def user_logout(request):
#     #Since we know the user is logged  in, we can now just log them out
#     logout(request)
#     # Take the user back to the homepage
#     return redirect(reverse('rango:index'))

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'rango/restricted.html')

# def user_login(request):
#     # If the request is HTTP POST, try to pull out the relevant information
#     if request.method == 'POST':
#         # Gather the username and password provided by the user
#         # This information is obtained from the login form.
#         # We use request.POST.get('<variable>') as opposed
#         # to request.POST['<variable>'] because the
#         # request.POST.get('<variable>') returns None if the
#         # value does not exist, while request.POST['<variable>']
#         # will raise a KeyError exception
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         #Use Django's machinery to attempt to see if the username/password
#         #combination is valid -  a User object is  returned if it is.
#         user = authenticate(username=username, password=password)
#
#         # If we have a User object, the  details  are  correct
#         # If None *Python's  way of representing the absence of a value). no user
#         # with matching credentials was found
#         if user:
#             # Is the account active? It could have been disabled
#             if user.is_active:
#                 # If the account is valid and active, we can log the user in
#                 # We'll send the user back to the homepage
#                 login(request, user)
#                 return redirect(reverse('rango:index'))

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
  Add a Category
{% endblock %}

{% block body_block %}

  <div class="jumbotron p-4">
    <div class="container">
      <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
  </div>

  <div class="container">
      <div class="row">
        <form role="form" id="category_form" action="{% url 'rango:add_category' %}" method="post" novalidate>
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
            <div class="p-2">
            </div>
          {% endfor %}
          <br>
          <button class="btn btn-primary" type="submit" name="submit">Add a Category</button>
          <div class="p-5"></div>
        </form>
      </div>
  </div>
  <div>
  </div>
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      Rango -
      {% block title_block %}
        How to Tango with Django!
      {% endblock %}
    </title>
  </head>
  <body>
    <div>
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>
     {% block body_block %}
     {% endblock %}
     <hr>
     <div>
       <ul>
         {% if user.is_authenticated %}
           <!-- Show these links when the user is logged in -->
           <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
           <li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
           <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
           <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
         {% else %}
          <!-- Show these links when the user is NOT logged in -->
          <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
          <li><a href="{% url 'auth_login' %}">Login</a></li>
        {% endif %}
          <!-- Outside the conditional statements, ALWAYS show -->
          <li><a href="{% url 'rango:about' %}">About</a></li>
          <li><a href="{% url 'rango:index' %}">Index</a></li>
      </ul>
     </div>
  </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        <!-- <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li> -->
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <!-- <li class="nav-item"><a class="nav-link" href="{% url 'rango:register_profile' %}">Register Here</a></li> -->
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="w-75 ml-3">
                      <input type="search"
                             id="search-input"
                             class="form control ds-input"
                             placeholder="Search..." />
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>

        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
  {% if categories %}
    {% for c in categories %}
      {% if c == current_category %}
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
          <span data-feather="archive"></span>
          {{ c.name }}
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
          <span data-feather="archive"></span>{{ c.name }}
        </a>
      </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li class="nav-item">There are no categories present.</li>
  {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
  {% if category %}
    {{ category.name }}
  {% else %}
    Unknown Category
  {% endif %}
{% endblock %}

{% block body_block %}
{% if category %}
  <div class="jumbotron p-4">
      <div class="container">
          <h1 class="jumbotron-heading">{{ category.name }}</h1>

          <!-- AJAX chapter likes button component. DM. -->
          <div>
              <strong id="like_count">{{ category.likes }}</strong> likes
              {% if user.is_authenticated %}
              <button id="like_btn" data-categoryid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                  <span data-feather="thumbs-up"></span>
                  Like Category
              </button>
              {% endif %}
          </div>
      </div>
  </div>

  {% if pages %}
  <div id="page-listing">
    <ul>
      {% for page in pages %}
      <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a></li>
        {% if page.views > 1 %}
          ({{ page.views }} views)
        {% elif page.views == 1 %}
          ({{ page.views}} view)
        {% endif %}
      {% endfor %}
    </ul>
  </div>
  {% else %}
  <strong>No pages currently in category.</strong>
  {% endif %}

  <!-- {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a> <br>
  {% endif %} -->

  {% if user.is_authenticated %}
    <div>
      <form class="form-inline"
            id="user-form"
            action="{% url 'rango:show_category' category.slug %}"
            method="post">
        {% csrf_token %}

        <div class="form-group">
          <input class="form-control"
                 type="text"
                 name="query"
                 size="50"
                 id="query"
                 value="{{ query }}" />
        </div>

        <button class="btn btn-primary"
                type="submit"
                name="submit">Search</button>
      </form>
    </div>
    <div>
      {% if result_list %}
        <h2>Results</h2>
        <div class="list-group">
          {% for result in result_list %}
            <div class="list-group-item">
              <h3 class="list-group-item-heading">
                <a href="{{ result.link }}">
                  {{ result.title|safe|escape}}
                </a>
              </h3>
              <button class="btn btn-info btn-sm rango-page-add"
                      type="button"
                      data-categoryid="{{ category.id }}"
                      data-title="{{ result.title }}"
                      data-url="{{ result.link }}">
                      Add
              </button>
              <p class="list-group-item-text">
                {{ result.summary|safe|escape }}
              </p>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  {% endif %}



  {% else %}
  The specified category does not exist.
  {% endif%}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
  Homepage
{% endblock %}

{% block body_block %}

  <div class="jumbotron p-4">
    <div class="container">
      <h1>Rango says...</h1>
      <div>
        <h2 class="h2">
          {% if user.is_authenticated %}
            howdy {{ user.username }}!
          {% else %}
            hey there partner!
          {% endif %}
        </h2>
        <strong>{{boldmessage}}</strong>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-6">
          <div class="card-body">
            <h2>Most Liked Categories</h2>
            <p class="card-text">
              {% if categories %}
              <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item">
                  <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                </li>
                {% endfor %}
              </ul>
              {% else %}
              <strong>There are no categories present.</strong>
              {% endif %}
            </p>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="card mb-6">
          <div class="card-body">
            <h2>Most Viewed Pages</h2>
            <p class="card-text">
              {% if pages %}
              <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item">
                  <a href="{{ page.url }}">{{ page.title }}</a>
                </li>
                {% endfor %}
              </ul>
              {% else %}
              <strong>There are no pages present.</strong>
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <img src="{{ MEDIA_URL }}rango.jpg" alt="Picture of Rango" />
  </div>
{% endblock %}

<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <title>Rango</title>
  </head>
  <body>
    <h1>Rango says...</h1>
    <div>
      hey there partner! <br />
      <strong>{{boldmessage}}</strong><br />
    </div>

    <div>
      <h2>Most Liked Categories</h2>
      {% if categories %}
      <ul>
        {% for category in categories %}
        <li>
          <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <strong>There are no categories present.</strong>
      {% endif %}
    </div>

    <div>
      <h2>Most Viewed Pages</h2>
      {% if pages %}
      <ul>
        {% for page in pages %}
        <li>
          <a href="{{ page.url }}">{{ page.title }}</a>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <strong>There are no pages present.</strong>
      {% endif %}
    </div>

    <div>
      <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
  </body>
</html>

templates/rango/page_listing.html
{% if pages %}
  <ul>
    {% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a></li>
      {% if page.views > 1 %}
        ({{ page.views }} views)
      {% elif page.views == 1 %}
        ({{ page.views}} view)
      {% endif %}
    {% endfor %}
  </ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}